### ISSUE TITLE
difference of gradient orientations

### ISSUE THREAD

**Issue by bootchk** [kkduncan/SaliencyDetection#2]
Using the minus operator for float types holding gradient orientations (angular coordinate of polar coordinates) in units of radians yields either the interior (small) or exterior (large) subtended angle, depending on the order of the operands.  Instead, using the function atan2(sin(x-y), cos(x-y)) gives the smallest angle, and seems to give crisper saliency results.  

This issue might have crept in during your translation from legacy code to openCV and polar coordinates.  I just stumbled upon this as I was working on color gradients.

I am surprised openCV does not have an Angle class with this method.

[http://stackoverflow.com/questions/1878907/the-smallest-difference-between-2-angles(url)

**Comment by kkduncan** [comment]
Please indicate to me where I used polar coordinates. I don't recall using polar coordinates at all. Nonetheless, I will apply your suggestion and observe the results.

**Comment by kkduncan** [comment]
I do get _crisper_ results by incorporating your suggestion. I will update my end with that change.
